# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hack2' do
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'Hero'
  pod 'SwiftyJSON'
end

use_frameworks!
