# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hack2' do
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.2'
  pod 'Hero', '~> 0.3'
end

use_frameworks!
